x <- c(10, 20, 30, 40, 50, 60, 60, 70, 80, 90, 100)
cat('Data Set is', x)
cat('\n\nMean:', mean(x))
cat('\nMedian:', median(x))
cat('\n\n')
data <- table(x)
print(data)
print(names(data))
mode <- names(data)[which.max(data)]
cat("\nMode:", mode)
cat('\n\n')
q1 <- quantile(x, 0.25)
q2 <- quantile(x, 0.5)
q3 <- quantile(x, 0.75)
cat('\nQ1:', q1)
cat('\nQ2:', q2)
cat('\nQ3:', q3)
cat('\n\nInterquartile Range:', IQR(x))
md <- sum(abs(x - mean(x))) / length(x)
cat('\n\nMean Deviation:', md)
cat('\n\nStandard Deviation:', sd(x))
cat('\n\nVariance:', var(x))
